### ISSUE TITLE
Recreating the Default Resource .Abk files

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#10]
notes:

DBL_Editor
Insert_DBL

**Comment by marc365** [comment]
It is a manual process to build the resource banks and they are data/images and dbl scripts in a resource bank, tools have been made available by BruceUncle to put them together and edit them, the source code for the bank is inside the bank and can be extracted with the tools etc. these tools could be maintained in a separate repository, the existing documention should be added and linked from a dedicated wiki.
