### ISSUE TITLE
Remove 'Locate_APSystem.AMOS'?

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#11]
+interpreter_config.s has the security codes "PId1" and "PIt1" (Code de securite!)

these are used to check version compatibility and they are referenced in Locate_APSystem.AMOS used to find and replace "APSystem/" with a hardcoded path. The program also looks in the hardcoded path location "s:" for the +interpreter_config.s file.

Locate_APSystem.AMOS was used previously as part of the installation - I am proposing the removal of this installation step so that +interpreter_config.s always has only "APSystem/" as the location for it's system files.

when Amos loads it creates the assign AMOSPro_System: automatically and looks for "APSystem" in this location. when Amos runs with this default setting it allows multiple instances of Amos to be installed on the same machine - the benefits of multiple configurations and multiple extension configurations exist when you don't hardcode the settings.

leaving the default configuration in s: and storing the loaded configuration in AMOSPro_System: (next to AMOSPro executable) works out-of-the-box without reconfiguration and installs perfectly.

there is also a branch/proposal for a minor tweak of the order in which the locations are searched to load these files (update to follow)

note: the compiler always loads the default files from s: and loads AMOS.library from LIBS: only, it will complain if it can't load the library so it must be installed there, even though Amos was running and loaded the library from "APSystem/".

note: the interprefer config accessory has a button that says to "load the default configuration" which it will do from s: - but it isn't totaly clear to the user, unless they are aware of a multi-settings environment they may save the setting and reload without having them changed, as Amos loads the s: setting as a secondary search location.

**Comment by marc365** [comment]
ok, i've just gone through a redeployment and have changed my mind here and we should leave it the same, but I will add something to the documentation regarding this at a later point as it is probably useful for "advanced" users.
