### ISSUE TITLE
Icons.Abk, info.abk, Object_Pics.Abk, Install_Banks.Abs

### ISSUE THREAD

**Issue by marc365** [AmosFactory/AmosProfessional#33]
these files are in the temp folder, I want to delete them.

Icons.Abk is full of mermaids and sea vessels, not sure how useful this is?
info.abk is not recognized by any of the accessories, using a hex editor it looks like a collection of palettes
Object_Pics.Abk is not recognized by any of the accessories, using a hex editor it looks like an image

info.abk and Object_Pics.Abk both have a bank name of "Datas" instead of the allowable "Data" (section 14.E.02 AMOSPro Manual) - Datas is spotted in 1.36 Creator class banks.

Install_Banks.Abs is from the compiler install disk, and the compiler is now always installed and configured.

**Comment by mness1978** [comment]
I think Icons.Abk is just an example icon bank (as opposed to a sprite bank).  It may still be useful as an example.

Object_Pics.Abk sounds like a packed picture bank (that is a thing, right?  I remember reading about it in the manual but never used the feature).

Are any of these banks used in any of the example or help programs?

**Comment by marc365** [comment]
none of these the files are in use anymore

**Comment by mness1978** [comment]
Well, then I vote to delete them also.

**Comment by marc365** [comment]
👍 good thing is they are never gone when in a git repo anyway.
