### ISSUE TITLE
Max string length

### ISSUE THREAD

**Issue by marc365** [AmosFactory/AmosProfessional#34]
is the string length restricted to 1024 characters? in the source of Object_Editor.AMOS line 1250

 A$=String$(" ",1024)

**Comment by SamuraiCrow** [comment]
The maximum string length should be 32768 or thereabouts.

**Comment by mness1978** [comment]
Sam's right, it's definitely more than 1024.  The size is a 16-bit quantity, I'm just not sure if it's signed or unsigned (I thought I read somewhere in the manual that the max string length was 65,535 characters, but I am getting old so Alzheimer's may be setting in).  There are certainly AMAL and DBL programs that are longer than 1024 characters.

**Comment by marc365** [comment]
thanks.
