### ISSUE TITLE
Commiting Bogus Code

### ISSUE THREAD

**Issue by marc365** [AmosFactory/AmosProfessional#35]
The menu contribution had a mistake, it claimed that one of the fields is used to make the menu item active or non-active - this is not true, the menu becomes non-active when the Func is set to 0000

yeh, I fixed it.

All code is tested before being commited, any mistakes like this will be highlighted, but the idea of commiting bogus code and commenting that this is how something works is not professional and won't get past me.

if you want AMOS to have a future, all commits from developers need to function correctly, do not just work against the text files assuming you are doing it correctly, that wastes my time and ruins reputations.

**Comment by marc365** [comment]
I need to understand why this happened - would it possible to make a short video of what was observed that made the field to be understood as a active field - the data was re-created perfectly, so this confuses me more that worries - the note above is more for future developers who join than a fix, can you help me?

**Comment by mness1978** [comment]
I'm confused.  Who committed bogus code?

**Comment by marc365** [comment]
did you see the

"click the "Load the Diff" button for +editor_config.s and you will see it."

comment yet, the contributed files are merged perfectly into +editor_config.s, It took much longer than it should as the file was heavily wrapped in doc, which would have been more helpfull in a text file. the issue is becuase this "issue" has begun with this first contribution (sic commit recurrsive issue) that I have commited (waiting for review and merge)  so spending time reading all the text then applying and testing and finding it not to be true is frustrating, also just looking at the spot where the code can be merged everything makes sence, so alot of time wasted onthing that would be documented for the next generation and would be false, stuff like that can bring the whole projects reputation down so I appologise for being strong but i'm looking after my ass.

**Comment by mness1978** [comment]
Ok, so this was BruceUncle's code that was merged (well, not merged yet, but the pull request was created)?  Right?  I understand your concern there.  I think most of us who work with code professionally understand the need to test thoroughly before pushing changes.  Good catch.  Has your fix for this been pushed to the editor-config-menu-upgrade branch yet?

**Comment by marc365** [comment]
thanks, yes it is in there - i relabeled the headers on the MnMacro to show the unused field.

**Comment by marc365** [comment]
it is a good contribution, just untested...

**Comment by mness1978** [comment]
> i relabeled the headers on the MnMacro to show the unused field.

Line 1343-1345?
