### ISSUE TITLE
3d extension does not work

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#4]
it builds but it does not function - it may be from the previous version of Amos

**Comment by AmosFactory** [comment]
It does now...

I did a manual binary compare of the original with my build, found tiny differences, and traced those in the source code to RJmp - then found out there is a conversion mechanism for references like L_ErrorExt  - "Table de conversion des labels AMOSPro 1.0 >>> AMOSPro 2.0" - but we don't have the AMOSPro 1.0 references, but AMOS The Creator ones worked - magic!

**Comment by SamuraiCrow** [comment]
How should extension sources be set up in this repository?  Should they be separate?

**Comment by marc365** [comment]
I guess it only depends on how many, what it is, and if everyone else wants it added as a core component. I'd suggest that any core components we add should be in the main build with scripts and any configuration changes needed all set up ready to run, but I think most should have a repo of their own.

if the extension has more than one source file make a folder for it, but keep the build script in the root.

also another thing to think about is that having extensions in separate repos maximizes their visibility, if they are in the core they would disappear (for most users at least) - I think there is more value in offering the extensions as separate entities...

**Comment by mness1978** [comment]
I would vote to make the 3D extension a core component.  3D is no longer a curiosity, it is an integral part of gaming today.  Including 3D as part of the main distribution makes it more visible to us as developers.

**Comment by SamuraiCrow** [comment]
Since this is a closed issue, we should continue the discussion elsewhere.

**Comment by mness1978** [comment]
In what sense is it closed?  Does the 3D extension work now?  Have we decided where it should go?  Reopening for further discussion.

**Comment by marc365** [comment]
thanks for administrating, appreciated.

this is a core plugin - can't think of a reason why it wouldn't be in there?

"It does now..." 

yes it's working :-)

the success commits were referenced, they say "successfully rebuilt", but it hasn't actually been through testing yet, so in truth I can only confirm that it builds and loads as an extension successfully.

I assume that each part of the system needs testing before we release the next version, so I don't think there's any need to focus specifically on this one yet, but it would be good to know if it actually functions as it should, if anyone has any 3d demos/games we could use to test please upload and link them here if you can, I will also see if I have anything appropriate...

**Comment by mness1978** [comment]
Ah, yes, I missed the "successfully rebuilt AMOSPro_3d.Lib" message back there.  Very good.

I think I have some old 3D code on some adfs I could use.  And I know the original 1.3 version of the 3D extension had a bunch of demos that we could use to test.  I'll see what I can dig up.

Not directly related, but does anyone know if the source to OM was ever released?

**Comment by SamuraiCrow** [comment]
I've only just looked through the Amos3D manual PDF this morning and I like what I see.  In terms of using 16 bit fixed point angles and global space coordinates always it should be fast.  Quaternion arithmetic is faster anyway.  The downside is that making matrix calculations allows more flexibility in having joints and bone structures in the models.  It may be due for a rewrite.

**Comment by marc365** [comment]
sounds good. remeber the actual 3d code is in c3d.lib, its a 'C' library not written in assembler - it would be intense to rewrite, but I do support the idea.

I attempted to rebuilt it for The Creator as well, but no joy so far, it needs a reference to Sys_Pathname which is in Pro so that is parked for now.

and, not sure what 'OM' is?

**Comment by SamuraiCrow** [comment]
OM is the name of the Object Modeller.  If it weren't for the floating-point requirement, Irrlicht would be a nice graphics engine to wrap but it would require a Vampire as a bare minimum requirement.

**Comment by marc365** [comment]
I just looked it up and found a cross reference of this: 

Antiryad Gx
http://www.arkham-development.com/wiki.htm?id=agx

**Comment by mness1978** [comment]
Attached is a zip file containing the AMOS 3D demos from the original AMOS 3D distribution.  Hopefully they can serve as a decent set of tests for development.

[AMOS_3D_demos.zip](https://github.com/AmosFactory/AmosProfessional/files/994619/AMOS_3D_demos.zip)

**Comment by marc365** [comment]
Great, I'll try them as soon as I can. Can you add them to the repo to the examples folder, start a new issue to discuss uploads if you need to, or just go for it, I think new files are fine and these are authentic AMOS historical items 👍

**Comment by SamuraiCrow** [comment]
Antiryad GX has license issues that make it unsuitable for open source.

**Comment by marc365** [comment]
the demos are trying to load the 3d objects from the disk - I had a look and I don't have them, do you?

**Comment by mness1978** [comment]
> the demos are trying to load 3d objects from the disk - I had a look and I don't have them, do you?

See pull request #23, somehow the objects folder was omitted in my archive above.  It is included in the commit though.

**Comment by marc365** [comment]
note: this 3d extension seems very particular about the path to the objects. 

the code says:
```

Ld Dir ":AMOS_3d_demos/objects"
Ld Load "car1"
```

and when trying to run it doesn't find the file "car1" until I change the path to:

`Ld Dir "DH0:AMOS_3d_demos/objects"
`

you can't assume that your in the folder and set the path to just "objects", it always needs a full path.
it works with an assign, so as a quick fix I suggest changing all the demos to have "AMOSPro_3d:AMOS_3d_demos/objects" and making the 3d assign happen during startup integrating it more into the core.
