### ISSUE TITLE
The new +Dialog_Funcs and Editor_Menus files are larger than the previous ones

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#6]
Genim2 generates a 196 byte file and reports that it has assembled 158 bytes, which is the same as the existing one - but when running Get_Chunk the size at long word 28 is 160 bytes, so when it is extracted there are 2 extra bytes at the end which can't be accounted for - the old Get_Chunk command produces the same effect. Attemting to remove the last 2 bytes from the sourcecode made the bin file 156 bytes long. There may be an assembler option needed for byte alignment - or a variation of the Get_Chunk command might be required.

If the larger files are use the generated AMOSPro.Lib file is different - so they have been ommited from the build script until resolved.

relates to: https://github.com/AmosFactory/AmosProfessional/commit/d6c3bb7e80236cdec2be46254337ed471ce9e476 https://github.com/AmosFactory/AmosProfessional/commit/c567c8ab01d8f0538c3084175f40aa59bf3649de https://github.com/AmosFactory/AmosProfessional/commit/8255ef1e3ac0856135019794e8611126400b1be4

**Comment by marc365** [comment]
I tried to find a reference to the conversation, but couldn't - I believe it was mentioned that these files could be included instead of incbined - Bruce's recreated sourcecode can replace the .bin build step.

**Comment by marc365** [comment]
Menu complete: https://github.com/AmosFactory/AmosProfessional/pull/32
