### ISSUE TITLE
+pro2.s is a code fragment from +b.s

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#7]
could remove it, or replace the code in +b.s with an 'Include'?

**Comment by marc365** [comment]
a code comparison shows they are not the same code, it may be from version 1.00 as there much more code in +b.s and there is a line that says:


;	Une librarie 2.0?
; ~~~~~~~~~~~~~~~~~~~~~~~

this is in +b.s and not +pro2.s - the differences are highlighted using the [diff tool WinMerge](https://github.com/AmosFactory/AmosProfessional/issues/14).

the file is useful for reference purposes so should stay in temp/.
