### ISSUE TITLE
'Clean_Original_Sources_20170407' not applied yet

### ISSUE THREAD

**Issue by AmosFactory** [AmosFactory/AmosProfessional#9]
I've reviewed all the files, and I think they are not ready to apply to the main source yet for the following reasons:

1. adding a ';' character before end-of-line comments is not required by Genam to assemble, maybe there is something about the text editor used to create these, but it doesn't make reading comments any easier using GoldEd on the Amiga or Visual Studio Code.
2. the commenting is not consistent, there are still '*' characters used at the beginning of lines.
3. there is some extra sharding I noticed in +3d.s (there may be more) that was not there before.
4. the commenting out of debug code is a drastic change and I'd prefer to do it on a separate commit so it could be restored at a later date.
5. need to check why the 'IFNE Debug' part in +w.s is commented out - line 10119 - is this correct as I would assume that the code would be needed "if not in debug" mode? but i may have my 'stupid' hat on this morning.
6. there is a note in the readme that says the generated binaries are a different size, so it will be the first change to the distribution binaries...
7. and I'm concerned that it may interfere with tracking real changes, but that probably isn't a real issue.
 
I'll try and get this applied to the next update - would it be possible to separate the debug changes, or is it is too much work to do it like that?

ps. from the archive I can see that these reformatted source code files were used to produce some beautiful pdf documents which could be added to a new Research Documentation section if someone could maintain it?

**Comment by marc365** [comment]
I'm using these for quick references some times to see what the bleep has been going on, but they will be deleted eventually, the Debug issues are resolved, the text would cause too many problems merging, and confuses the update history. closing.
